/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NakamFood;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DBSS018
 */
public class NakamRestaurant extends javax.swing.JFrame {

    int TotalBiaya, Kurang;
    int opsi; // parameter opsi
    String telp, Resto;

    ArrayList<Integer> idProd;
    ArrayList<Integer> cntProd;
    ArrayList<String> namaProd;

    // create hashmap untuk passing value
    // 4 key (id produk) [maks]
    // 4 value (dari count1234) [maks]

    /**
     * Creates new form NakamRestaurant
     */
    public NakamRestaurant() {
        inisialisasi();
    }

    // konstruktor parameter opsi
    public NakamRestaurant(int opsi, String telpon) {
        this.opsi = opsi;
        this.telp = telpon;
        inisialisasi();
    }

    public NakamRestaurant(String telp, String Resto) {
        this.telp = telp;
        this.Resto = Resto;
        inisialisasi();
    }

    public void inisialisasi() {
        idProd = new ArrayList<>();
        cntProd = new ArrayList<>();
        namaProd = new ArrayList<>();
        initComponents();
        Menu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        orderButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        NamaResto = new javax.swing.JLabel();
        alamatResto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tabelDftrMenu = new javax.swing.JTable();
        Plus1 = new javax.swing.JButton();
        Minus1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Plus2 = new javax.swing.JButton();
        Minus2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Plus3 = new javax.swing.JButton();
        Minus3 = new javax.swing.JButton();
        Plus4 = new javax.swing.JButton();
        Minus4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel4.setText("Total");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Rp");

        harga.setBackground(new java.awt.Color(255, 255, 255));
        harga.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        harga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        harga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel4)
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(harga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(harga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        orderButton.setBackground(new java.awt.Color(0, 255, 255));
        orderButton.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        orderButton.setForeground(new java.awt.Color(255, 255, 255));
        orderButton.setText("ORDER");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 0, 0));
        backButton.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBar(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        NamaResto.setFont(new java.awt.Font("Comic Sans MS", 1, 35)); // NOI18N
        NamaResto.setForeground(new java.awt.Color(0, 0, 255));

        alamatResto.setBackground(new java.awt.Color(0, 255, 255));
        alamatResto.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        alamatResto.setForeground(new java.awt.Color(51, 204, 255));
        alamatResto.setText("Alamat Restoran");
        alamatResto.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                alamatRestoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tabelDftrMenu.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        tabelDftrMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", ""},
                {"", "", ""},
                {"", "", ""},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Nama Nakam", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelDftrMenu.setRowHeight(30);
        tabelDftrMenu.setShowHorizontalLines(false);
        tabelDftrMenu.setShowVerticalLines(false);

        Plus1.setBackground(new java.awt.Color(51, 255, 255));
        Plus1.setForeground(new java.awt.Color(51, 51, 255));
        Plus1.setText("+");
        Plus1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                Plus1InputMethodTextChanged(evt);
            }
        });
        Plus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plus1ActionPerformed(evt);
            }
        });

        Minus1.setBackground(new java.awt.Color(255, 0, 0));
        Minus1.setFont(new java.awt.Font("Yu Gothic Light", 0, 11)); // NOI18N
        Minus1.setForeground(new java.awt.Color(255, 255, 255));
        Minus1.setText("-");
        Minus1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                Minus1InputMethodTextChanged(evt);
            }
        });
        Minus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Minus1ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Plus2.setBackground(new java.awt.Color(0, 255, 255));
        Plus2.setForeground(new java.awt.Color(51, 51, 255));
        Plus2.setText("+");
        Plus2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                Plus2InputMethodTextChanged(evt);
            }
        });
        Plus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plus2ActionPerformed(evt);
            }
        });

        Minus2.setBackground(new java.awt.Color(255, 0, 0));
        Minus2.setFont(new java.awt.Font("Yu Gothic Light", 0, 11)); // NOI18N
        Minus2.setForeground(new java.awt.Color(255, 255, 255));
        Minus2.setText("-");
        Minus2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                Minus2InputMethodTextChanged(evt);
            }
        });
        Minus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Minus2ActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Plus3.setBackground(new java.awt.Color(0, 255, 255));
        Plus3.setForeground(new java.awt.Color(51, 51, 255));
        Plus3.setText("+");
        Plus3.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                Plus3InputMethodTextChanged(evt);
            }
        });
        Plus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plus3ActionPerformed(evt);
            }
        });

        Minus3.setBackground(new java.awt.Color(255, 0, 0));
        Minus3.setFont(new java.awt.Font("Yu Gothic Light", 0, 11)); // NOI18N
        Minus3.setForeground(new java.awt.Color(255, 255, 255));
        Minus3.setText("-");
        Minus3.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                Minus3InputMethodTextChanged(evt);
            }
        });
        Minus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Minus3ActionPerformed(evt);
            }
        });

        Plus4.setBackground(new java.awt.Color(0, 255, 255));
        Plus4.setForeground(new java.awt.Color(51, 51, 255));
        Plus4.setText("+");
        Plus4.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                Plus4InputMethodTextChanged(evt);
            }
        });
        Plus4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plus4ActionPerformed(evt);
            }
        });

        Minus4.setBackground(new java.awt.Color(255, 0, 0));
        Minus4.setFont(new java.awt.Font("Yu Gothic Light", 0, 11)); // NOI18N
        Minus4.setForeground(new java.awt.Color(255, 255, 255));
        Minus4.setText("-");
        Minus4.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                Minus4InputMethodTextChanged(evt);
            }
        });
        Minus4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Minus4ActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alamatResto)
                            .addComponent(NamaResto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tabelDftrMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Plus4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Plus3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Minus3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Minus4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Plus1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Plus2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Minus2)
                                    .addComponent(Minus1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 28, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NamaResto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamatResto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelDftrMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Plus1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Minus1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Plus2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Minus2))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Plus3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Minus3))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Plus4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Minus4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))))
                .addContainerGap())
        );

        if (tabelDftrMenu.getColumnModel().getColumnCount() > 0) {
            tabelDftrMenu.getColumnModel().getColumn(0).setMinWidth(30);
            tabelDftrMenu.getColumnModel().getColumn(0).setPreferredWidth(30);
            tabelDftrMenu.getColumnModel().getColumn(0).setMaxWidth(30);
            tabelDftrMenu.getColumnModel().getColumn(2).setMinWidth(125);
            tabelDftrMenu.getColumnModel().getColumn(2).setPreferredWidth(125);
            tabelDftrMenu.getColumnModel().getColumn(2).setMaxWidth(125);
        }

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(492, 492, 492))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(629, 629, 629))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        String alamatTujuan;
        alamatTujuan = JOptionPane.showInputDialog("Alamat Pesanan: ");
        
        JOptionPane.showMessageDialog(null, "Order diterima!");
        NakamOrder klikOrder;
        try {
            klikOrder = new NakamOrder(idProd, cntProd, namaProd, Resto, telp, TotalBiaya, alamatTujuan);
            klikOrder.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(NakamRestaurant.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_orderButtonActionPerformed

    private void Plus1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_Plus1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Plus1InputMethodTextChanged


    private void Plus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plus1ActionPerformed
        int val = cntProd.get(0);
        cntProd.set(0, ++val);

        Object Harga = tabelDftrMenu.getValueAt(0, 2);
//        System.out.println("Harga" + Harga);
        Double hrg = Double.parseDouble((String) Harga);
        TotalBiaya += hrg;

        String s = String.valueOf(TotalBiaya);
        harga.setText(s);
        String jumlah = String.valueOf(val);
        jLabel8.setText(jumlah);
    }//GEN-LAST:event_Plus1ActionPerformed

    private void Minus1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_Minus1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Minus1InputMethodTextChanged

    private void Minus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Minus1ActionPerformed
        int val = cntProd.get(0);

        Object Harga = tabelDftrMenu.getValueAt(0, 2);
//        System.out.println("Harga" + Harga);

        int hrg = (int) Math.floor(Double.parseDouble((String) Harga));
        cntProd.set(0, --val);

        if (val < 0) {
            cntProd.set(0, 0);
        } else {
            TotalBiaya -= hrg;//50000 bisa diganti harga dari database oi
            if (TotalBiaya < 0) {
                TotalBiaya = 0;
            }
        }

        String t = String.valueOf(TotalBiaya);
        String jumlah = String.valueOf(cntProd.get(0));
        jLabel8.setText(jumlah);
        harga.setText(t);
    }//GEN-LAST:event_Minus1ActionPerformed

    private void Plus2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_Plus2InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Plus2InputMethodTextChanged

    private void Plus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plus2ActionPerformed
        int val = cntProd.get(1);
        cntProd.set(1, ++val);

        Object Harga = tabelDftrMenu.getValueAt(1, 2);
//        System.out.println("Harga" + Harga);

        Double hrg = Double.parseDouble((String) Harga);
        TotalBiaya += hrg;

        //50000 bisa diganti harga dari database oi
        String s = String.valueOf(TotalBiaya);
        harga.setText(s);
        String jumlah = String.valueOf(cntProd.get(1));
        jLabel11.setText(jumlah);
    }//GEN-LAST:event_Plus2ActionPerformed

    private void Minus2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_Minus2InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Minus2InputMethodTextChanged

    private void Minus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Minus2ActionPerformed
        int val = cntProd.get(1);

        Object Harga = tabelDftrMenu.getValueAt(1, 2);
//        System.out.println("Harga" + Harga);
        Double hrg = Double.parseDouble((String) Harga);
        cntProd.set(1, --val);

        if (val < 0) {
            cntProd.set(1, 0);
        } else {
            TotalBiaya -= hrg;//50000 bisa diganti harga dari database oi
            if (TotalBiaya < 0) {
                TotalBiaya = 0;
            }
        }

        String t = String.valueOf(TotalBiaya);
        harga.setText(t);

        String jumlah = String.valueOf(cntProd.get(1));
        jLabel11.setText(jumlah);
    }//GEN-LAST:event_Minus2ActionPerformed

    private void Plus3InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_Plus3InputMethodTextChanged

    }//GEN-LAST:event_Plus3InputMethodTextChanged

    private void Plus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plus3ActionPerformed
        int val = cntProd.get(2);
        cntProd.set(2, ++val);

        Object Harga = tabelDftrMenu.getValueAt(2, 2);
//        System.out.println("Harga" + Harga);
        Double hrg = Double.parseDouble((String) Harga);
        TotalBiaya += hrg;
        //50000 bisa diganti harga dari database oi
        String s = String.valueOf(TotalBiaya);
        harga.setText(s);
        String jumlah = String.valueOf(cntProd.get(2));
        jLabel12.setText(jumlah);
    }//GEN-LAST:event_Plus3ActionPerformed

    private void Minus3InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_Minus3InputMethodTextChanged
    }//GEN-LAST:event_Minus3InputMethodTextChanged

    private void Minus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Minus3ActionPerformed
        int val = cntProd.get(2);

        Object Harga = tabelDftrMenu.getValueAt(2, 2);
//        System.out.println("Harga" + Harga);
        Double hrg = Double.parseDouble((String) Harga);
        cntProd.set(2, --val);

        if (val < 0) {
            cntProd.set(2, 0);
        } else {
            TotalBiaya -= hrg;//50000 bisa diganti harga dari database oi
            if (TotalBiaya < 0) {
                TotalBiaya = 0;
            }
        }
        String t = String.valueOf(TotalBiaya);

        harga.setText(t);

        String jumlah = String.valueOf(cntProd.get(2));
        jLabel12.setText(jumlah);
    }//GEN-LAST:event_Minus3ActionPerformed

    private void alamatRestoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_alamatRestoAncestorAdded
        // TODO add your handling code here:
        NakamPemesanan s = new NakamPemesanan(opsi);
        NakamCariMakanan M = new NakamCariMakanan(Resto, telp);
        String AlamatResto = s.getPemesanan();
        if (M.getPemesanan() != null) {
            AlamatResto = M.getPemesanan();
        }
        try {
            // to do preepared statement
            String sql = "SELECT alamat FROM restoran where nama_tempat = '" + AlamatResto + "'";
            java.sql.Connection conn = (Connection) konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                String name = res.getString("alamat");
                alamatResto.setText(name);

            }

        } catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }//GEN-LAST:event_alamatRestoAncestorAdded

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        NakamPemesanan NP = new NakamPemesanan(this.telp);
        NP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void Plus4InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_Plus4InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Plus4InputMethodTextChanged

    private void Plus4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plus4ActionPerformed
        int val = cntProd.get(3);
        cntProd.set(3, ++val);

        Object Harga = tabelDftrMenu.getValueAt(3, 2);
//        System.out.println("Harga" + Harga);

        Double hrg = Double.parseDouble((String) Harga);
        TotalBiaya += hrg;
        //50000 bisa diganti harga dari database oi
        String s = String.valueOf(TotalBiaya);
        harga.setText(s);
        String jumlah = String.valueOf(cntProd.get(3));
        jLabel13.setText(jumlah);
    }//GEN-LAST:event_Plus4ActionPerformed

    private void Minus4InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_Minus4InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Minus4InputMethodTextChanged

    private void Minus4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Minus4ActionPerformed
        int val = cntProd.get(3);

        Object Harga = tabelDftrMenu.getValueAt(3, 2);
//        System.out.println("Harga" + Harga);

        Double hrg = Double.parseDouble((String) Harga);
        cntProd.set(3, --val);

        if (val < 0) {
            cntProd.set(3, 0);
        } else {
            TotalBiaya -= hrg;//50000 bisa diganti harga dari database oi
            if (TotalBiaya < 0) {
                TotalBiaya = 0;
            }
        }

        String t = String.valueOf(TotalBiaya);
        harga.setText(t);
        String jumlah = String.valueOf(cntProd.get(3));
        jLabel13.setText(jumlah);
    }//GEN-LAST:event_Minus4ActionPerformed

    private void Menu() {

        NakamPemesanan s = new NakamPemesanan(opsi);
        NakamCariMakanan M = new NakamCariMakanan(Resto, telp);
        DefaultTableModel barisTabelMenu = (DefaultTableModel) tabelDftrMenu.getModel();
        // inisialisasi nama resto
        barisTabelMenu.setRowCount(0);
        String NamaRestoran = s.getPemesanan();
        if (M.getPemesanan() != null) {
            NamaRestoran = M.getPemesanan();
        }
        if (Resto == null) {
            Resto = NamaRestoran;
        }
//        System.out.println("restonya = " + Resto);
        try {
            // prepared statement
            // ambil id produk 
            String sql = "SELECT id_produk, deskripsi,harga FROM produk where nama_tempat = '" + NamaRestoran + "'";

            java.sql.Connection conn = (Connection) konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            // nomor
            Integer no = 1;
            while (res.next()) {
                // tambah id ke arraylist
                idProd.add(Integer.parseInt(res.getString(1)));
                cntProd.add(0);
                namaProd.add(res.getString(2));
                // untuk tampilin
                barisTabelMenu.addRow(new Object[]{no++, res.getString(2), res.getString(3)});

            }

            NamaResto.setText(NamaRestoran);

        } catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NakamRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NakamRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NakamRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NakamRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        NakamPemesanan s = new NakamPemesanan();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NakamRestaurant().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Minus1;
    private javax.swing.JButton Minus2;
    private javax.swing.JButton Minus3;
    private javax.swing.JButton Minus4;
    private javax.swing.JLabel NamaResto;
    private javax.swing.JButton Plus1;
    private javax.swing.JButton Plus2;
    private javax.swing.JButton Plus3;
    private javax.swing.JButton Plus4;
    private javax.swing.JLabel alamatResto;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton orderButton;
    private javax.swing.JTable tabelDftrMenu;
    // End of variables declaration//GEN-END:variables
}
