/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NakamFood;

import static NakamFood.NakamLogin.url;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DBSS028
 */
public class NakamRegister extends javax.swing.JFrame {

    private JFrame frame;

    static String url = "jdbc:sqlserver://localhost:1433;databaseName=nakam_food;integratedSecurity=true";
    static String userName = "";
    static String password = "";

    //Connect to DB
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement st;

    /**
     * Creates new form NakamRegister
     */
    public NakamRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtSurel = new javax.swing.JTextField();
        jtxtNoTelp = new javax.swing.JTextField();
        jtxtDepan = new javax.swing.JTextField();
        jtxtTengah = new javax.swing.JTextField();
        jtxtBelakang = new javax.swing.JTextField();
        jbtCancel = new javax.swing.JButton();
        jbtOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTER", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 36))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel1.setText("Inisial Tengah");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 280, 40));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel2.setText("Nomor Telepon (+62)");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 370, 40));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel3.setText("Surel");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 280, 40));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel4.setText("Nama Depan");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 280, 40));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel5.setText("Nama Belakang");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 280, 40));

        jtxtSurel.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jtxtSurel.setToolTipText("");
        jPanel6.add(jtxtSurel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 340, 40));

        jtxtNoTelp.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jtxtNoTelp.setToolTipText("");
        jPanel6.add(jtxtNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 340, 40));

        jtxtDepan.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jtxtDepan.setToolTipText("");
        jPanel6.add(jtxtDepan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 340, 40));

        jtxtTengah.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jtxtTengah.setToolTipText("");
        jPanel6.add(jtxtTengah, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 340, 40));

        jtxtBelakang.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jtxtBelakang.setToolTipText("");
        jPanel6.add(jtxtBelakang, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 340, 40));

        jbtCancel.setBackground(new java.awt.Color(255, 0, 0));
        jbtCancel.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jbtCancel.setForeground(new java.awt.Color(255, 255, 255));
        jbtCancel.setText("Cancel");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });
        jPanel6.add(jbtCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 610, 190, 50));
        jbtCancel.getAccessibleContext().setAccessibleName("Batalkan");

        jbtOk.setBackground(new java.awt.Color(51, 255, 0));
        jbtOk.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jbtOk.setForeground(new java.awt.Color(255, 255, 255));
        jbtOk.setText("Ok");
        jbtOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOkActionPerformed(evt);
            }
        });
        jPanel6.add(jbtOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, 190, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1087, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOkActionPerformed
        String noTelp = jtxtNoTelp.getText();
        String namaDepan = jtxtDepan.getText();
        String inisialTengah = jtxtTengah.getText();
        String namaBelakang = jtxtBelakang.getText();
        String surel = jtxtSurel.getText();
        int log = 0;

        try {
            conn = DriverManager.getConnection(url);
            String query = "INSERT INTO pelanggan VALUES(?,?,?,?,?)";
            st = conn.prepareStatement(query);

            st.setString(1, noTelp);
            st.setString(2, namaDepan);
            st.setString(3, inisialTengah);
            st.setString(4, namaBelakang);
            st.setString(5, surel);
            if (noTelp.equals("") || namaDepan.equals("") || namaBelakang.equals("") || surel.equals("")) {
                JOptionPane.showMessageDialog(null, "There's one or more empty field(s)!", "Nakam Food Login System", JOptionPane.INFORMATION_MESSAGE);
            }else if (st.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "Acccount Registered!", "Nakam Food Login System", JOptionPane.INFORMATION_MESSAGE);
                log = 1;
                this.dispose();
            }
            if (log == 1) {
                NakamLogin info = new NakamLogin();
                info.setVisible(true);
            }

        } catch (SQLException ex) {
            Logger.getLogger(NakamRegister.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbtOkActionPerformed
    
    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit? ", "Nakam Food Login System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NakamRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NakamRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NakamRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NakamRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NakamRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtOk;
    private javax.swing.JTextField jtxtBelakang;
    private javax.swing.JTextField jtxtDepan;
    private javax.swing.JTextField jtxtNoTelp;
    private javax.swing.JTextField jtxtSurel;
    private javax.swing.JTextField jtxtTengah;
    // End of variables declaration//GEN-END:variables
}
