/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NakamFood;

import static NakamFood.NakamPelanggan.url;
import static NakamFood.NakamRegister.url;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DBSS028
 */
public class NakamEdit extends javax.swing.JFrame {

    static String url = "jdbc:sqlserver://localhost:1433;databaseName=nakam_food;integratedSecurity=true";
    static String userName = "";
    static String password = "";

    //Connect to DB
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement st;
    Statement stt;

    static String noTelp;

    /**
     * Creates new form NakamEdit
     */
    public NakamEdit() {
        initComponents();
    }

    public NakamEdit(String s) {
        noTelp = s;
        initComponents();
        setField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtNamaDepan = new javax.swing.JTextField();
        jtxtInisialTengah = new javax.swing.JTextField();
        jtxtNamaBelakang = new javax.swing.JTextField();
        jtxtSurel = new javax.swing.JTextField();
        jbtCancel = new javax.swing.JButton();
        jbtOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Akun Anda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 24))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setText("Inisial Tengah");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setText("Nama Depan");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel3.setText("Nama Belakang");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel4.setText("Surel");

        jtxtNamaDepan.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jtxtNamaDepan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNamaDepanActionPerformed(evt);
            }
        });

        jtxtInisialTengah.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jtxtInisialTengah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtInisialTengahActionPerformed(evt);
            }
        });

        jtxtNamaBelakang.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jtxtNamaBelakang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNamaBelakangActionPerformed(evt);
            }
        });

        jtxtSurel.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jtxtSurel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSurelActionPerformed(evt);
            }
        });

        jbtCancel.setBackground(new java.awt.Color(255, 0, 0));
        jbtCancel.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jbtCancel.setForeground(new java.awt.Color(255, 255, 255));
        jbtCancel.setText("Batalkan");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });

        jbtOk.setBackground(new java.awt.Color(51, 255, 0));
        jbtOk.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jbtOk.setForeground(new java.awt.Color(255, 255, 255));
        jbtOk.setText("Ok");
        jbtOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtSurel, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(jtxtNamaBelakang)
                            .addComponent(jtxtInisialTengah)
                            .addComponent(jtxtNamaDepan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jbtOk, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jbtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(143, 143, 143))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNamaDepan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtInisialTengah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNamaBelakang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSurel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtOk, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOkActionPerformed
        // TODO add your handling code here:
        namaDepan = jtxtNamaDepan.getText();
        inisialTengah = jtxtInisialTengah.getText();
        namaBelakang = jtxtNamaBelakang.getText();
        surel = jtxtSurel.getText();

        int log = 0;

        try {
            conn = DriverManager.getConnection(url);
            String query = "UPDATE pelanggan SET nama_depan = ?, inisial_tengah = ?, nama_belakang = ?, surel = ? WHERE telepon_pelanggan = ?";
            st = conn.prepareStatement(query);

            st.setString(1, namaDepan);
            st.setString(2, inisialTengah);
            st.setString(3, namaBelakang);
            st.setString(4, surel);
            st.setString(5, noTelp);
            if (st.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "Acccount Updated!", "Nakam Food", JOptionPane.INFORMATION_MESSAGE);
                log = 1;
                this.dispose();
            }
            if (log == 1) {
                NakamPelanggan info = new NakamPelanggan(noTelp);
                info.setVisible(true);
            }

        } catch (SQLException ex) {
            Logger.getLogger(NakamRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtOkActionPerformed

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        // TODO add your handling code here:
        NakamPelanggan info = new NakamPelanggan(noTelp);
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtCancelActionPerformed

    private void jtxtSurelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSurelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSurelActionPerformed

    private void jtxtNamaBelakangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNamaBelakangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNamaBelakangActionPerformed

    private void jtxtInisialTengahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtInisialTengahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtInisialTengahActionPerformed

    private void jtxtNamaDepanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNamaDepanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNamaDepanActionPerformed

    String namaDepan, inisialTengah, namaBelakang, surel;
    
    private void setField() {
        try {
            conn = DriverManager.getConnection(url);
            String query = "SELECT * FROM pelanggan where telepon_pelanggan like ?";
            st = conn.prepareStatement(query);

            st.setString(1, noTelp);
            rs = st.executeQuery();
            while (rs.next()) {
                surel = rs.getString("surel");
                jtxtSurel.setText(surel);
                namaBelakang = rs.getString("nama_belakang");
                jtxtNamaBelakang.setText(namaBelakang);
                inisialTengah = rs.getString("inisial_tengah");
                jtxtInisialTengah.setText(inisialTengah);
                namaDepan = rs.getString("nama_depan");
                jtxtNamaDepan.setText(namaDepan);
                jtxtSurel.setVisible(true);
                jtxtSurel.repaint();
                jtxtSurel.validate();
            }
        } catch (SQLException ex) {
            Logger.getLogger(NakamEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NakamEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NakamEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NakamEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NakamEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NakamEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtOk;
    private javax.swing.JTextField jtxtInisialTengah;
    private javax.swing.JTextField jtxtNamaBelakang;
    private javax.swing.JTextField jtxtNamaDepan;
    private javax.swing.JTextField jtxtSurel;
    // End of variables declaration//GEN-END:variables
}
